# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170421_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
